version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"
    networks:
      - my-network

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-python-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
